name: Run Test

on:
 pull_request:
  branches: [main]

jobs:
 build:
   runs-on: ubuntu-latest

   steps:
    - name: checkout
      uses: actions/checkout@v4.2.1

    - name: Setup JDK 17
      uses: actions/setup-java@v4.4.0
      with:
        java-version: 17
        distribution: temurin
        cache: gradle

    - name: Grant execute permissions for gradlew
      run: chmod +x gradlew

    - name: Run unit tests
      run: ./gradlew test

    - name: Upload Test Report
      uses: actions/upload-artifact@v4.4.3
      with:
        name: test-report
        path: build/reports/tests/testReleaseUnitTest/index.html

    - name: Run Build
      run: ./gradlew bundleRelease
        

     
   
